#include <algorithm>
#include <memory>
#include <string>
#include <unordered_map>
#include <vector>

#include "simulator.h"
#include "trading_day.h"


void StockMarketSimulation::run(){
    for (; trading_day < trading_days; trading_day++){
        auto todays_data = advance();
        handle(todays_data);
    }

}


std::vector<StockTrades> SimpleTimeBarDailySimulation::advance(){
    /* Advances by 1 trading day*/
    int daily_volume_per_stock = volume;
    auto raw_prices = market->get_next_n_prices(daily_volume_per_stock, timestep);

    auto tickers = market->get_tickers();

    std::vector<StockTrades> todays_data = {};

    for (auto & stock_ticker : tickers){
        auto& prices = raw_prices->at(stock_ticker);
        TradingDay trading_day;
        for (auto price : prices){
            trading_day.add_transaction(price);
        }
        todays_data.push_back({stock_ticker, trading_day});
    }

    return todays_data;
}   

void SimpleTimeBarDailySimulation::handle(std::vector<StockTrades> &todays_data){
    /* Handles the data generated by the simulation for a single trading day.*/
    for (auto & stock_history : todays_data){
        auto & ticker = stock_history.ticker;
        auto & trades = stock_history.trades;
        auto daily_bar = trades.get_daily_data();
        trading_day_data.at(ticker).push_back(daily_bar);
    }

}

